name: CI Workflow

# Define when the workflow will run
on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger for pull requests targeting the 'main' branch

env:
  DOCKER_IMAGE_NAME: saaignment3-Namrata
  HF_SPACE_REPO_URL: https://huggingface.co/spaces/Namratakghodke/Housing_Price
  SONAR_PROJECT_KEY: namrata_assi3
  SONAR_ORGANIZATION: placework459
  SONAR_HOST_URL: https://sonarcloud.io/organizations/placework459/projects

# Define the jobs that will run in this workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java 17 (to avoid the Java version compatibility issue)
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Set Java version to 17
          distribution: 'adoptopenjdk'  # Ensure you use a compatible JDK distribution (AdoptOpenJDK)

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the Python version to use

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust based on your dependencies

      # Step 5: Run tests
      - name: Run Pytest with coverage and html report
        run: |      
          pytest

      # Step 6: SonarQube Scan
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          args: -X  # Enable debug logging for more information
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ env.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ env.SONAR_ORGANIZATION }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
