name: CI Workflow

# Define when the workflow will run
on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger for pull requests targeting the 'main' branch

env:
  DOCKER_IMAGE_NAME: saaignment3-Namrata
  HF_SPACE_REPO_URL: https://huggingface.co/spaces/Namratakghodke/Housing_Price
  SONAR_PROJECT_KEY: namrataonlinetrainingorg
  SONAR_ORGANIZATION: placework459
  SONAR_HOST_URL: https://sonarcloud.io/organizations/placework459/projects

# Define the jobs that will run in this workflow
jobs:
  build:
    # This defines the environment to run the job on (ubuntu-latest, windows-latest, etc.)
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the Python version to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust based on your dependencies

       # Step 4: Run tests
      - name: Run Pytest with coverage and html report
        run: |      
          pytest 
          
      

           # Step 5: SonarQube Scan
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ env.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ env.SONAR_ORGANIZATION }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
